/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.publicDonation;

import Business.Enterprise.Enterprise;
import Business.Enterprise.OrphanageEnterprise;
import Business.Organization.DonationsOrganisation;
import Business.Organization.Organization;
import Business.Organization.PublicDonationOrganization;
import Business.RandomFiles.Donar;
import Business.RandomFiles.DonarDirectory;
import Business.RandomFiles.DonationAddWorkRequest;
import Business.RandomFiles.Status;
import Business.UserAccount.UserAccount;
import Businesss.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sudheer Reddy Gaddam
 */
public class PublicDonationRequestOrphanage extends javax.swing.JPanel {

     private JPanel rightJPanel;
    private PublicDonationOrganization publicDonationOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private String receiver;
    /**
     * Creates new form PublicDonationRequest
     */
    public PublicDonationRequestOrphanage(JPanel righJPanel, PublicDonationOrganization publicDonationOrganization, 
            Enterprise enterprise, UserAccount userAccount, EcoSystem business,String receiver) {
        initComponents();
        this.rightJPanel = righJPanel;
        this.publicDonationOrganization = publicDonationOrganization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        this.receiver = receiver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        amountTxtField = new javax.swing.JTextField();
        mailTxtField = new javax.swing.JTextField();
        addrTxtField = new javax.swing.JTextField();
        donateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<replace_by_enterprise_name>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 21)); // NOI18N
        jLabel1.setText("Enter the Donar Details ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel3.setText("Amount:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel4.setText("Email Id:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel5.setText("Address:");

        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });

        amountTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtFieldActionPerformed(evt);
            }
        });

        donateBtn.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        donateBtn.setText("Donate");
        donateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donateBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTxtField)
                                    .addComponent(amountTxtField)
                                    .addComponent(mailTxtField)
                                    .addComponent(addrTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(valueLabel)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(amountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addrTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donateBtn)
                    .addComponent(backBtn))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void donateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtnActionPerformed
       
        //Check the empty format and amount greater than zero
        
        if(nameTxtField.getText() == null || nameTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Name can't be null or empty!!");
        }
        
        if(mailTxtField.getText() == null || mailTxtField.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "mail Id cannot be empty or null");
        }
        
        if(addrTxtField.getText() == null || addrTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Address cannot be null or empty");
        }
        
        if(amountTxtField.getText()== null || amountTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Amount cannot be empty or null");
        }
        try{
        int amt = Integer.parseInt(amountTxtField.getText());
        if(amt < 0){
            JOptionPane.showMessageDialog(null, "Amount cannot be less than zero");
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Aount can to be only integer value without decimals");
        }
        
        //Check for email format!!!
        
        DonarDirectory donarDirectory = publicDonationOrganization.getDonarDirectory();
        
//        if(donarDirectory.getDonarList() == null){
//            donarDirectory.addDonar();
//            publicDonationOrganization.setDonarDirectory(donarDirectory);
//        }
        
        //donarDirectory.addDonar();
        Donar donar =  donarDirectory.addDonar();
        
        donar.setAddress(addrTxtField.getText());
        donar.setEmailId(mailTxtField.getText());
        donar.setName(nameTxtField.getText());
        donar.setAmount(Integer.parseInt(amountTxtField.getText()));

        
        
        DonationAddWorkRequest donationAddWorkRequest = new DonationAddWorkRequest();
        donationAddWorkRequest.hashCode();
        donationAddWorkRequest.setSender(userAccount);
        donationAddWorkRequest.setRequestDate(new Date());
        donationAddWorkRequest.setStatus("Sent");
        donationAddWorkRequest.setMessage(donar);
        
        //Fetch organisation which is donationsorganisation in 
     
        Organization donationOrganisation = null;
        for (Enterprise e : business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof OrphanageEnterprise) {
                for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof DonationsOrganisation) {
                        donationOrganisation = organization;
                        break;
                    }
                }
            }
        }
        
        
        if (donationOrganisation!=null){
            donationOrganisation.getWorkQueue().getWorkRequestList().add(donationAddWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(donationAddWorkRequest);
        }
        

        
        
        
        JOptionPane.showMessageDialog(this, "Donation has been sent to Orphange. Will soon be processed");
        nameTxtField.setText("");
        addrTxtField.setText("");
        mailTxtField.setText("");
        amountTxtField.setText("");
        
    }//GEN-LAST:event_donateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        
        
        
        //Populaye the data in the layout
        Component[] components = rightJPanel.getComponents();
        
        for(Component c : components){
            if(c instanceof PublicDonationManager){
                ((PublicDonationManager) c).populateRequestTable();
            }
        }
        
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        rightJPanel.remove(this);
        layout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void amountTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrTxtField;
    private javax.swing.JTextField amountTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton donateBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mailTxtField;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
