/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.publicDonation;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.PublicDonationOrganization;
import Business.RandomFiles.Donar;
import Business.RandomFiles.DonationAddWorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Businesss.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utkarsh
 */
public class PublicDonationManager extends javax.swing.JPanel {

    /**
     * Creates new form PublicDonationManager
     */
    private JPanel rightJPanel;
    private PublicDonationOrganization publicDonationOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public PublicDonationManager(JPanel righJPanel, PublicDonationOrganization publicDonationOrganization, 
            Enterprise enterprise, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.rightJPanel = righJPanel;
        this.publicDonationOrganization = publicDonationOrganization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        populateRequestTable(); //this actually populate the donos till now in the table
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationsListTable = new javax.swing.JTable();
        donateOrphangePublicBtn = new javax.swing.JButton();
        donateOldAgeHomeBtn = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<replace_by_enterprise_name>");

        donationsListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Donor Name", "Amount", "Date", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(donationsListTable);

        donateOrphangePublicBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        donateOrphangePublicBtn.setText("Donate to Orphanage");
        donateOrphangePublicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateOrphangePublicBtnActionPerformed(evt);
            }
        });

        donateOldAgeHomeBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        donateOldAgeHomeBtn.setText("Donate to Old Age Home");
        donateOldAgeHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateOldAgeHomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(valueLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(donateOrphangePublicBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donateOldAgeHomeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(donateOrphangePublicBtn)
                .addGap(18, 18, 18)
                .addComponent(donateOldAgeHomeBtn)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donateOrphangePublicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateOrphangePublicBtnActionPerformed
           
        //After populating data, we move to next screen 
        
            CardLayout layout = (CardLayout)rightJPanel.getLayout();
            rightJPanel.add(new PublicDonationRequestOrphanage( rightJPanel,  publicDonationOrganization, 
             enterprise,  userAccount,  business,"orphanage"));
            layout.next(rightJPanel);
        
    }//GEN-LAST:event_donateOrphangePublicBtnActionPerformed

    private void donateOldAgeHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateOldAgeHomeBtnActionPerformed
        
    }//GEN-LAST:event_donateOldAgeHomeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donateOldAgeHomeBtn;
    private javax.swing.JButton donateOrphangePublicBtn;
    private javax.swing.JTable donationsListTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    public void populateRequestTable() {
        
        
        //Populate the table
        
        DefaultTableModel model = (DefaultTableModel) donationsListTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()){
            Donar d = (Donar)workRequest.getMessage();
            Object[] row = new Object[5];
                    row[0] = d;
                    row[1] = d.getAmount();
                    row[2] = String.valueOf(workRequest.getRequestDate());
                    row[3] = null;
                    row[4] = "Sent";
                    model.addRow(row);
        }
        
        
        
    }
}
