/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EventManagement;

import Business.Enterprise.Enterprise;
import Business.Organization.DonationsOrganisation;
import Business.Organization.EventManagementOrganisation;
import Business.RandomFiles.Donar;
import Business.RandomFiles.DonationAddWorkRequest;
import Business.RandomFiles.EventInEventManagement;
import Business.RandomFiles.EventInEventMangDirectory;
import Business.Role.EventType;
import Business.UserAccount.UserAccount;
import Businesss.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.publicDonation.PublicDonationRequestOrphanage;

/**
 *
 * @author Utkarsh
 */
public class EventManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventManagerJPanel
     */
    private JPanel rightJPanel;
    private EventManagementOrganisation eventManagementOrganisation;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public EventManagerJPanel(JPanel rightJPanel,EventManagementOrganisation organization, Enterprise enterprise,UserAccount userAccount,EcoSystem business) {
        initComponents();
        //MM/dd/yyyy HH:mm
        this.rightJPanel = rightJPanel;
        this.eventManagementOrganisation = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        valueLabel.setText(organization.getName());
        populateEventsTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updateEventBtn = new javax.swing.JButton();
        evntDateTime = new javax.swing.JTextField();
        deleteEvntBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventsTbl = new javax.swing.JTable();
        HealthCareBtn = new javax.swing.JButton();
        AddEventBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        eventTypeBox = new javax.swing.JComboBox<String>();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 184, 69));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Schedule Event:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Event date and Time:");

        updateEventBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        updateEventBtn.setText("Update");

        evntDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evntDateTimeActionPerformed(evt);
            }
        });

        deleteEvntBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deleteEvntBtn.setText("Delete");
        deleteEvntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEvntBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Event Name:");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Organization:  ");

        eventsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Scheduled date", "Type"
            }
        ));
        jScrollPane1.setViewportView(eventsTbl);

        HealthCareBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HealthCareBtn.setText("Health care!!");
        HealthCareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthCareBtnActionPerformed(evt);
            }
        });

        AddEventBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        AddEventBtn.setText("Add ");
        AddEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Event Type");

        eventTypeBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        eventTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cultural", "SexualAwareness", "Sports" }));

        valueLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        valueLabel.setText("<change_it_to_name_of_org>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(AddEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateEventBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteEvntBtn)
                        .addGap(69, 69, 69)
                        .addComponent(HealthCareBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(eventTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(87, 87, 87)
                        .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(evntDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valueLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eventTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(evntDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEventBtn)
                    .addComponent(updateEventBtn)
                    .addComponent(deleteEvntBtn)
                    .addComponent(HealthCareBtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void evntDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evntDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evntDateTimeActionPerformed

    private void HealthCareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthCareBtnActionPerformed
         
            CardLayout layout = (CardLayout)rightJPanel.getLayout();
            rightJPanel.add(new EventManagerHealthJPanel(rightJPanel,  eventManagementOrganisation, 
             enterprise,  userAccount,  business));
            layout.next(rightJPanel);
    }//GEN-LAST:event_HealthCareBtnActionPerformed

    private void AddEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventBtnActionPerformed
        
        EventType eventType = EventType.valueOf(String.valueOf(eventTypeBox.getSelectedItem()));
        String name = eventName.getText();
        String date = evntDateTime.getText();
        
        if(eventManagementOrganisation.getEventInEventMangDirectory() == null){
            eventManagementOrganisation.setEventInEventMangDirectory(new EventInEventMangDirectory());
        }
        
        EventInEventManagement eventInEventManagement = eventManagementOrganisation.getEventInEventMangDirectory().addEventInEventManagement();
        
        eventInEventManagement.setDateTime(date);
        eventInEventManagement.setEventType(eventType);
        eventInEventManagement.setName(name);
        
        populateEventsTable();
        
        eventName.setText("");
        evntDateTime.setText("");
        
        
        
    }//GEN-LAST:event_AddEventBtnActionPerformed

    private void deleteEvntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEvntBtnActionPerformed
        int selectedRow = eventsTbl.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }
        EventInEventManagement eventInEventManagement = (EventInEventManagement) eventsTbl.getValueAt(selectedRow, 0);
        eventManagementOrganisation.getEventInEventMangDirectory().getEventInEventManagements().remove(eventInEventManagement);
        populateEventsTable();
        

    }//GEN-LAST:event_deleteEvntBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventBtn;
    private javax.swing.JButton HealthCareBtn;
    private javax.swing.JButton deleteEvntBtn;
    private javax.swing.JTextField eventName;
    private javax.swing.JComboBox<String> eventTypeBox;
    private javax.swing.JTable eventsTbl;
    private javax.swing.JTextField evntDateTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateEventBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    private void populateEventsTable() {

        DefaultTableModel model = (DefaultTableModel) eventsTbl.getModel();
        model.setRowCount(0);

        if (eventManagementOrganisation.getEventInEventMangDirectory() == null || 
                eventManagementOrganisation.getEventInEventMangDirectory().getEventInEventManagements() == null) {
            JOptionPane.showMessageDialog(this, "No events are scheduled !!!");
            return;
        }

        for (EventInEventManagement e : eventManagementOrganisation.getEventInEventMangDirectory().getEventInEventManagements()) {
            Object[] row = new Object[3];
            row[0] = e;
            row[1] = e.getDateTime();
            row[2] = e.getEventType().getValue();
            model.addRow(row);
        }
    }
}
