/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DonationOrganization;

import Business.Enterprise.Enterprise;
import Business.Organization.DonationsOrganisation;
import Business.Organization.HealthCareOrganization;
import Business.RandomFiles.Child;
import Business.RandomFiles.ExpenseManagerWorkRequest;
import Business.RandomFiles.ExpenseObject;
import Business.RandomFiles.SendToGovtHealthCareWorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Businesss.EcoSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utkarsh
 */
public class ExpenseManager extends javax.swing.JPanel {

    /**
     * Creates new form ExpenseManager
     */
    private JPanel rightJPanel;
    private DonationsOrganisation donationsOrganisation;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    
    public ExpenseManager(JPanel rightJPanel, DonationsOrganisation organization, Enterprise enterprise, UserAccount userAccount, EcoSystem business) {
        initComponents();
        
        this.rightJPanel = rightJPanel;
        this.donationsOrganisation = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        populateExpRequests();
        valLable.setText(donationsOrganisation.getName());
        availableFundTotal.setText(String.valueOf(donationsOrganisation.getAvailableFund()));
        expAmountTotal.setText(String.valueOf(donationsOrganisation.getTotalExpenditure()));
        availableFundTotal.setEnabled(false);
        expAmountTotal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availableFundTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        expTbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        approvBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        expAmountTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        valLable = new javax.swing.JLabel();

        availableFundTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableFundTotalActionPerformed(evt);
            }
        });

        expTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Purpose", "Amount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(expTbl);

        jLabel6.setText("Total Available Funds: ");

        approvBtn.setText("Approve");
        approvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvBtnActionPerformed(evt);
            }
        });

        jButton6.setText("Disapprove");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Expenditure: ");

        expAmountTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expAmountTotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Organization: ");

        valLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valLable.setText("value_label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(expAmountTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(availableFundTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(approvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(valLable)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valLable))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approvBtn)
                    .addComponent(jButton6))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableFundTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(expAmountTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void availableFundTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableFundTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableFundTotalActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        int selectedRow = expTbl.getSelectedRow();
        
        if (selectedRow < 0) {
            return;
        }
        ExpenseManagerWorkRequest request = (ExpenseManagerWorkRequest) expTbl.getValueAt(selectedRow, 0);
        if (request.getStatus().equalsIgnoreCase("Sent")) {
            request.setStatus("DisApproved");
            //donationsOrganisation.setTotalExpenditure(donationsOrganisation.getTotalExpenditure() + Integer.valueOf(request.getMessage().getAmount()));
            //donationsOrganisation.setAvailableFund(donationsOrganisation.getAvailableFund() - Integer.valueOf(request.getMessage().getAmount()));
        } else if (request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Disapproved")) {
            JOptionPane.showMessageDialog(this, "Action already been taken on the selected");
        }
        
        populateExpRequests();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void approvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvBtnActionPerformed
        int selectedRow = expTbl.getSelectedRow();
        
        if (selectedRow < 0) {
            return;
        }
        ExpenseManagerWorkRequest request = (ExpenseManagerWorkRequest) expTbl.getValueAt(selectedRow, 0);
        if (request.getStatus().equalsIgnoreCase("Sent")) {
            request.setStatus("Approved");
            donationsOrganisation.setTotalExpenditure(donationsOrganisation.getTotalExpenditure() + Integer.valueOf(request.getMessage().getAmount()));
            donationsOrganisation.setAvailableFund(donationsOrganisation.getAvailableFund() - Integer.valueOf(request.getMessage().getAmount()));
        } else if (request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Disapproved")) {
            JOptionPane.showMessageDialog(this, "Action already been taken on the selected");
        }
        populateExpRequests();

    }//GEN-LAST:event_approvBtnActionPerformed

    private void expAmountTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expAmountTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expAmountTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvBtn;
    private javax.swing.JTextField availableFundTotal;
    private javax.swing.JTextField expAmountTotal;
    private javax.swing.JTable expTbl;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valLable;
    // End of variables declaration//GEN-END:variables

    private void populateExpRequests() {
        
        DefaultTableModel model = (DefaultTableModel) expTbl.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest request : donationsOrganisation.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ExpenseManagerWorkRequest && request.getMessage() instanceof ExpenseObject) {
                
                ExpenseObject expObj = (ExpenseObject) request.getMessage();
                Object[] row = new Object[6];
                row[0] = request;
                row[1] = expObj.getPurpose();
                row[2] = expObj.getAmount();
                row[3] = request.getStatus();
                
                model.addRow(row);
            }
            
        }
        
    }
}
