/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DonationOrganization;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PublicEnterprise;
import Business.Organization.DonationsOrganisation;
import Business.Organization.Organization;
import Business.Organization.PublicDonationOrganization;
import Business.RandomFiles.Donar;
import Business.RandomFiles.DonationAddWorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Businesss.EcoSystem;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utkarsh
 */
public class FundManager extends javax.swing.JPanel {

    /**
     * Creates new form FundManager
     */
    private JPanel rightJPanel;
    private DonationsOrganisation donationsOrganisation;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public FundManager(JPanel righJPanel, DonationsOrganisation donationsOrganisation, Enterprise enterprise, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.rightJPanel = righJPanel;
        this.donationsOrganisation = donationsOrganisation;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        populateTable();
        valueLabel.setText(enterprise.getName());
        totalFundsTxt.setText(String.valueOf(donationsOrganisation.getAvailableFund()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fundManageTbl = new javax.swing.JTable();
        markPrcBtn = new javax.swing.JButton();
        totalFundsTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        fundManageTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Amount", "DonorName", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fundManageTbl);

        markPrcBtn.setText("Mark Processed");
        markPrcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markPrcBtnActionPerformed(evt);
            }
        });

        totalFundsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFundsTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total available funds ($) :");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<replace_by_enterprise_name>");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Request funds from Government");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(totalFundsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markPrcBtn)
                        .addGap(36, 36, 36)
                        .addComponent(deleteBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(valueLabel))))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markPrcBtn)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalFundsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalFundsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFundsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFundsTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        int selectedRow = fundManageTbl.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        DonationAddWorkRequest request = (DonationAddWorkRequest) fundManageTbl.getValueAt(selectedRow, 0);

        if (request.getStatus().equalsIgnoreCase("Received")) {
            donationsOrganisation.setAvailableFund(donationsOrganisation.getAvailableFund() - ((Donar) request.getMessage()).getAmount() < 0 ? 0
                    : donationsOrganisation.getAvailableFund() - ((Donar) request.getMessage()).getAmount());
        }
        donationsOrganisation.getWorkQueue().getWorkRequestList().remove(request);
        populateTable();


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void markPrcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markPrcBtnActionPerformed
        int selectedRow = fundManageTbl.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

       // DonationAddWorkRequest request = (DonationAddWorkRequest) fundManageTbl.getValueAt(selectedRow, 0);
       WorkRequest request = (WorkRequest) fundManageTbl.getValueAt(selectedRow, 0); 
     
       if (request.getStatus().equalsIgnoreCase("Sent")) {
            request.setReceiver(userAccount);
            request.setStatus("Received");
            request.setResolveDate(new Date());
            donationsOrganisation.setAvailableFund(donationsOrganisation.getAvailableFund() + ((Donar) request.getMessage()).getAmount());
            populateTable();
        }else if(request.getStatus().equalsIgnoreCase("received")){
            JOptionPane.showMessageDialog(null, "The selected row is already processed!!");
        }
        //Need to update the data of the sender also
        
        for(Enterprise e : business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList()){
            if(e instanceof PublicEnterprise){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof PublicDonationOrganization){
                         
                    }
                }
            }
        }
    }//GEN-LAST:event_markPrcBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     CardLayout layout = (CardLayout) rightJPanel.getLayout();
        rightJPanel.add("RequestLabTestJPanel", new ReqToGovJPanel( rightJPanel,  donationsOrganisation,  enterprise,  userAccount,  business));
        layout.next(rightJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTable fundManageTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markPrcBtn;
    private javax.swing.JTextField totalFundsTxt;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    //Popukate only those having donar as message object
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) fundManageTbl.getModel();

        model.setRowCount(0);

        for (WorkRequest request : donationsOrganisation.getWorkQueue().getWorkRequestList()) {
            if (request instanceof DonationAddWorkRequest && request.getMessage() instanceof Donar){
            
                Donar d = (Donar) request.getMessage();
                Object[] row = new Object[6];
                row[0] = request;
                row[1] = d.getAmount();
                row[2] = d.getName();
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[4] = request.getStatus();

                model.addRow(row);
            }

        }
        totalFundsTxt.setText(String.valueOf(donationsOrganisation.getAvailableFund()));
    }
}
