/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EducationOrganization;

import Business.Enterprise.Enterprise;
import Business.Organization.EducationOrganisation;
import Business.RandomFiles.Child;
import Business.RandomFiles.Donar;
import Business.RandomFiles.DonationAddWorkRequest;
import Business.RandomFiles.SendToEduConsuWorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Businesss.EcoSystem;
import DonationOrganization.CounsellorSolutionJPanel;
import DonationOrganization.ReqToGovJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utkarsh
 */
public class CounsellorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsultantJPanel
     */
    private JPanel rightJPanel;
    private EducationOrganisation educationOrganisation;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public CounsellorJPanel(JPanel righJPanel, EducationOrganisation educationOrganisation, Enterprise enterprise, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.rightJPanel = righJPanel;
        this.educationOrganisation = educationOrganisation;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;

        populateCounsellingRequest();
        jButton1.setBackground(Color.RED);
        jButton1.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        counsellorTabl = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        setLayout(null);

        counsellorTabl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        counsellorTabl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Student Name", "Issue/Concern", "Solution"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(counsellorTabl);

        add(jScrollPane1);
        jScrollPane1.setBounds(800, 0, 487, 214);

        jButton4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setDefaultCapable(false);
        jButton4.setFocusable(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(1150, 240, 107, 27);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setText("Update Solution");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.red, java.awt.Color.black, java.awt.Color.red));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(1010, 240, 107, 25);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Consultant.gif"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 4, 800, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int selectedRow = counsellorTabl.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
       // DonationAddWorkRequest request = (DonationAddWorkRequest) fundManageTbl.getValueAt(selectedRow, 0);
       SendToEduConsuWorkRequest sendToEduConsuWorkRequest = (SendToEduConsuWorkRequest) counsellorTabl.getValueAt(selectedRow, 0); 
       
       
       Child child = sendToEduConsuWorkRequest.getMessage();
        
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        rightJPanel.add("CounsellorSolutionJPanel", new CounsellorSolutionJPanel( rightJPanel, child,educationOrganisation));
        layout.next(rightJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable counsellorTabl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void populateCounsellingRequest() {

        DefaultTableModel model = (DefaultTableModel) counsellorTabl.getModel();
        model.setRowCount(0);

        for (WorkRequest request : educationOrganisation.getWorkQueue().getWorkRequestList()) {
            if (request instanceof SendToEduConsuWorkRequest && request.getMessage() instanceof Child) {

                Child d = (Child) request.getMessage();

                Object[] row = new Object[4];
                row[0] = request;
                row[1] = d.getName();
                row[2] = d.getCurrentProblem().getIssue();
                row[3] = d.getCurrentProblem().getSolution();
                model.addRow(row);
            }

        }

    }
}
