/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DonationOrganization;

import Business.Organization.EducationOrganisation;
import Business.RandomFiles.Child;
import EducationOrganization.CounsellorJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userInterface.publicDonation.PublicDonationManager;

/**
 *
 * @author Utkarsh
 */
public class CounsellorSolutionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CounsellorSolutionJPanel
     */
    private JPanel rightJPanel;
    private Child child;
    private EducationOrganisation educationOrganisation;
    
    public CounsellorSolutionJPanel(JPanel rightJPanel, Child child,EducationOrganisation educationOrganisation) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.child = child;
        this.educationOrganisation = educationOrganisation;
        label.setText(educationOrganisation.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        prescribedSolution = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 189, 69));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        setForeground(new java.awt.Color(255, 0, 0));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Organization: ");
        add(jLabel2);
        jLabel2.setBounds(85, 53, 105, 23);

        label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label.setText("value_label");
        add(label);
        label.setBounds(256, 53, 86, 23);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Suggested Solution:");
        add(jLabel1);
        jLabel1.setBounds(85, 139, 145, 25);
        add(prescribedSolution);
        prescribedSolution.setBounds(234, 130, 219, 43);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(272, 241, 153, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        child.getCurrentProblem().setSolution(prescribedSolution.getText());
        
        Component[] components = rightJPanel.getComponents();
        
        for(Component c : components){
            if(c instanceof CounsellorJPanel){
                ((CounsellorJPanel) c).populateCounsellingRequest();
            }
        }
        
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        rightJPanel.remove(this);
        layout.previous(rightJPanel);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField prescribedSolution;
    // End of variables declaration//GEN-END:variables
}
