/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Govt_HealthCare;

import Business.Enterprise.Enterprise;
import Business.Organization.EventManagementOrganisation;
import Business.Organization.HealthCareOrganization;
import Business.RandomFiles.Child;
import Business.RandomFiles.Donar;
import Business.RandomFiles.DonationAddWorkRequest;
import Business.RandomFiles.SendToGovtHealthCareWorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Businesss.EcoSystem;
import EventManagement.EventManagerHealthJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utkarsh
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    private JPanel rightJPanel;
    private HealthCareOrganization healthCareOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public DoctorJPanel(JPanel rightJPanel, HealthCareOrganization organization, Enterprise enterprise, UserAccount userAccount, EcoSystem business) {
        initComponents();

        this.rightJPanel = rightJPanel;
        this.healthCareOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        populateReceivedRequests();
        valueLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        assignToMeBtn = new javax.swing.JButton();
        processAndUpdateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 184, 69));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        setLayout(null);

        doctorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Student ID", "Issue", "Prescription", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(doctorTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(104, 81, 483, 167);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Organization:  ");
        add(jLabel1);
        jLabel1.setBounds(104, 30, 109, 23);

        valueLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        valueLabel.setText("<change_it_to_name_of_org>");
        add(valueLabel);
        valueLabel.setBounds(231, 30, 228, 23);

        assignToMeBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        assignToMeBtn.setText("Assign To Me");
        assignToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeBtnActionPerformed(evt);
            }
        });
        add(assignToMeBtn);
        assignToMeBtn.setBounds(104, 309, 119, 27);

        processAndUpdateBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        processAndUpdateBtn.setText("Process");
        processAndUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAndUpdateBtnActionPerformed(evt);
            }
        });
        add(processAndUpdateBtn);
        processAndUpdateBtn.setBounds(504, 309, 83, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeBtnActionPerformed
        
        int selectedRow = doctorTbl.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest sendToGovtHealthCareWorkRequest = (WorkRequest) doctorTbl.getValueAt(selectedRow, 0);
         if(sendToGovtHealthCareWorkRequest instanceof  SendToGovtHealthCareWorkRequest){
             sendToGovtHealthCareWorkRequest.setReceiver(userAccount);
         }
         
         populateReceivedRequests();
    }//GEN-LAST:event_assignToMeBtnActionPerformed

    private void processAndUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processAndUpdateBtnActionPerformed

        int selectedRow = doctorTbl.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        WorkRequest sendToGovtHealthCareWorkRequest = (WorkRequest) doctorTbl.getValueAt(selectedRow, 0);
        if(sendToGovtHealthCareWorkRequest.getReceiver() == null){
            JOptionPane.showMessageDialog(this, "Please get this assigned before processing!!");
        }
        if(sendToGovtHealthCareWorkRequest instanceof  SendToGovtHealthCareWorkRequest){
            
            CardLayout layout = (CardLayout)rightJPanel.getLayout();
            rightJPanel.add(new DoctorProcessJPanel(rightJPanel, (Child) sendToGovtHealthCareWorkRequest.getMessage(),healthCareOrganization,sendToGovtHealthCareWorkRequest,
                    enterprise,userAccount,business));
            layout.next(rightJPanel);
            
            
         }
        
        
        
    }//GEN-LAST:event_processAndUpdateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeBtn;
    private javax.swing.JTable doctorTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processAndUpdateBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    public void populateReceivedRequests() {

        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();

        model.setRowCount(0);

        for (WorkRequest request : healthCareOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof SendToGovtHealthCareWorkRequest && request.getMessage() instanceof Child){
            
                Child d = (Child) request.getMessage();
                Object[] row = new Object[6];
                row[0] = request;
                row[1] = d.getId();
                row[2] = d.getCurrentProblem().getIssue();
                row[3] = d.getCurrentProblem().getSolution();
                row[4] = request.getReceiver();
                row[5] = request.getStatus();

                model.addRow(row);
            }

        }


    }
}
